server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudstudy?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zhixi158
    # 应用名称 bookservice
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址（默认）
        server-addr: www.zhangzhixi.top:80
        # 将ephemeral修改为false，表示非临时实例（表示在服务挂掉之后，在Nacos中不会将服务显示清除）
        #ephemeral: false

        # 配置集群分区
        cluster-name: beijin
        # 配置Nacos命名空间
        #namespace: 21064619-da60-433c-a186-b07ec3d308e8
    # 将loadbalancer的nacos支持开启，集成Nacos负载均衡
    loadbalancer:
      nacos:
        enabled: true

    #sentinel流量控制
#    sentinel:
#      transport:
#        # 添加监控页面地址即可
#        dashboard: localhost:8858
#      # 将刚刚编写的请求映射设定为限流页面
#      block-page: /blocked
#      # 关闭Context收敛，这样被监控方法可以进行不同链路的单独控制
#      web-context-unify: false

#分布式事务-使用nacos方式部署
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: d2c0cd8c-0aaa-43f3-b752-1d4e7800fd04
      username: nacos
      password: nacos
      server-addr: www.zhangzhixi.top:80
  # 配置
  config:
    type: nacos
    nacos:
      namespace: d2c0cd8c-0aaa-43f3-b752-1d4e7800fd04
      username: nacos
      password: nacos
      server-addr: www.zhangzhixi.top:80